Repository Kurinku-Studios/FNF-Forward-Launcher, pull requests merged in 2021-07, with the labels that each got.

#32 Added Install path to installer
  .github/workflows/windows build.yml
  src/main/java/org/colonelkai/mod/Mod.java
Labels: bug

#43 Versioning
  .github/workflows/windows build.yml
  .gitignore
  src/main/java/org/colonelkai/StandAloneLauncher.java
  src/main/java/org/colonelkai/file/DataFile.java
  src/main/java/org/colonelkai/file/DataFileType.java
  src/main/java/org/colonelkai/file/DataNode.java
  src/main/java/org/colonelkai/file/json/simple/SimpleJsonFile.java
  src/main/java/org/colonelkai/file/simple/SimpleDataNode.java
  src/main/java/org/colonelkai/file/simple/SimpleRootDataNode.java
Labels: bug, documentation, enhancement

#44 Cancel Button
  src/main/java/org/colonelkai/guielements/nodes/downloadslist/DownloadBox.java
  src/main/java/org/colonelkai/mod/network/ZippedModDownloadTask.java
  src/main/java/org/colonelkai/tasks/getter/transfer/AbstractTransferTask.java
  src/main/java/org/colonelkai/tasks/getter/transfer/TransferTask.java
  src/main/java/org/colonelkai/tasks/getter/transfer/download/DownloadTask.java
  src/main/java/org/colonelkai/tasks/getter/transfer/download/InteruptableReadableByteChannel.java
Labels: enhancement
